### ISSUE TITLE
Ctrl+x & cut do not work in ace-editor, plus some questions

### ISSUE THREAD

**Issue by gettonet** [nk-crew/lazy-blocks#204]
### Issue description:
When using ctrl+x or "Cut" in editor, content gets removed but it cannot be pasted, instead we get "`<!-- wp:lzb-constructor/main /-->`" on paste.

### Lazy Blocks Version:
2.3.1

### WordPress Version:
5.7.1

Also, would be neat if we could restrict which Inner Blocks can be added inside Inner Block control. Is this something that could be filtered maybe?
Other than that, repeater in repeater is most wanted, I saw that last discussion about it was 2 years ago...any news on that?

I really enjoy using Lazy Blocks!

**Comment by nk-o** [comment]
Hey.

Yes, I know about this issue with copy/cut. I have checked it about half a year ago, but with no success. Something in Gutenberg code is conflicting with ours. Information about it placed in our private issues tracker.

Limitation for allowed blocks inside InnerBlocks control is planned for the Pro plugin.

What about repeaters inside repeaters - it is not in priority, as not many people are looking for this feature.

To be honest, this project is not our main priority (yet?), therefore no new features added and the Pro version is still is not released. I'm the only one who is working on this plugin in a free time because our team is focused on more popular projects like premium themes and the Visual Portfolio plugin. Unfortunately, as much as I love this plugin, I can't devote more time to it. That is why everything is dragging on so much.

Regards, nK.

**Comment by gettonet** [comment]
Thanks @nk-o,  I appreciate your time.
Help me understand something - I would like to import some data in my WP posts (content), and that data should include block markup.
Now, I have created a block that contains repeater, and when I open Code Editor it looks like this:
`<!-- wp:lazyblock/bc-menu-items {"category":"APPETIZERS","items":"%5B%7B%22title%22:%22VEGETABLE%20SPRING%20ROLLS%20-%202%20pcs.%22,%22price%22:%225%22%7D,%7B%22title%22:%22EGG%20ROLLS%20WITH%20PORK%20-%202%20pcs.%22,%22price%22:%227%22%7D,%7B%22title%22:%22FRIED%20SHRIMP%20WONTONS%20-%207%20pcs.%22,%22price%22:%229%22%7D,%7B%22title%22:%22FRIED%20PRAWN%20CRACKERS%22,%22price%22:%225%22%7D,%7B%22title%22:%22BBQ%20SPARE%20RIBS%22,%22price%22:%2212%22%7D,%7B%22title%22:%22HONEY%20GARLIC%20CHICKEN%20WINGS%20%22,%22price%22:%228%22%7D,%7B%22title%22:%22SWEET%20\u0026%20SOUR%20CHICKEN%20BALLS%22,%22price%22:%227%22%7D%5D","blockId":"Z1Q50RO","blockUniqueClass":"lazyblock-bc-menu-items-Z1Q50RO"} /-->`

after urldecode we have:
`<!--wp:lazyblock/bc-menu-items{"category":"APPETIZERS","items":"[{"title":"VEGETABLE SPRING ROLLS - 2 pcs.","price":"5"},{"title":"EGG ROLLS WITH PORK - 2 pcs.","price":"7"},{"title":"FRIED SHRIMP WONTONS - 7 pcs.","price":"9"},{"title":"FRIED PRAWN CRACKERS","price":"5"},{"title":"BBQ SPARE RIBS","price":"12"},{"title":"HONEY GARLIC CHICKEN WINGS ","price":"8"},{"title":"SWEET \u0026 SOUR CHICKEN BALLS","price":"7"}]","blockId":"Z1Q50RO","blockUniqueClass":"lazyblock-bc-menu-items-Z1Q50RO"}/-->`

BUT after urlencode it doesnt look like the original markup! And it gets deleted. 
How do I do this?
"items" is an array, e.g:
`$items= array('title' => 'VEGETABLE SPRING ROLLS - 2 pcs.', 'price' => '5');`

..so I thought this would do it:
`$my_block_markup = '<!-- wp:lazyblock/bc-menu-items {"category":"APPETIZERS","items":"';`
`$my_block_markup .= urlencode(json_encode($items));  // hERE IT IS`
`$my_block_markup .='","blockId":"Z1Q50RO","blockUniqueClass":"lazyblock-bc-menu-items-Z1Q50RO"}/-->';`

but no luck. Looks like not all characters should be urlencoded - I see that commas and colons are not urlencoded in the original, but I do not know how to achieve this.
Can you give me a guide on this?

**Comment by gettonet** [comment]
Oh boy...this might be an answer: https://jeremyfelt.com/2019/04/24/encoding-serialized-attributes-for-gutenberg-blocks-in-php/
