### ISSUE TITLE
What are the future plans?

### ISSUE THREAD

**Issue by hj-collab** [nk-crew/lazy-blocks#242]
Will there be more development to plugin? Is a pro version coming?

**Comment by nickfmc** [comment]
If I had to guess I would suspect a pro version to come out at some point and have some more Field types such as a post selector. that's a big one that is missing, if you wanted to pull in a list of Related posts etc. a Page link selector. However I'd love to also have an answer from the developer on this it is hard to count on a free tool because it could just stop working one day without warning

**Comment by nk-o** [comment]
Hey.

We are on the final steps in the Pro plugin development process. There will be additional fields like posts, taxonomies and user selectors, group fields and most requested feature - conditional logic for controls.

Currently, the priority is on our premium products and we can't actively work on free and not popular products.

Regards, nK.

**Comment by davidwebca** [comment]
Keep up the great work, I can't wait to shove my money in your wallet! (╯°□°）╯︵ 💰💰💰
