### ISSUE TITLE
Possible Name Change?

### ISSUE THREAD

**Issue by j7239** [nk-crew/lazy-blocks#253]
I'm having a hard time convincing my team this is a serious product just from the name alone. I personally think it's one of if not the simplest and cleanest way to work with custom blocks but when my team sees Lazy Blocks in the code or on the side menu it doesn't scream reliability or sustainability.
Maybe Easy Blocks or literally just Custom Blocks could be better.

**Comment by nk-o** [comment]
Hey.

Personally, I don't like the similarity with the images 'lazy loading' term. But I don't think these reasons are enough to change the plugin name for now.

I'll keep this issue open for a while to gather feedback. If more users are bothered by the name of the plugin, we'll consider renaming it.

**Comment by davidwebca** [comment]
I have to admit I had the same first thought, but in the end I equated "lazy" to "easy" in my head. It makes it really easy to it's a lazy task. 🤔  I still think it's a good name.

**Comment by jordymeow** [comment]
The plugin is awesome but the name doesn't represent what it does - its users aren't lazy neither :) Custom Blocks, Blocks Builder, Blocks Creator, Blocks Factory, there are an infinity of better name. This plugin is so good but I am afraid the name is way too misleading.

**Comment by nk-o** [comment]
I want to explain a little to you where this word in the name of the plugin came from. I didn't mean to offend or mislead anyone.

Initially, I created this plugin for myself to quickly create custom blocks for our premium themes, because I'm too lazy to create a separate plugin for each of our themes, which will contain specific blocks with React code and then spend time on supporting it when Gutenberg changes their API. And it works...

The blocks I created in 2018 still work today in 2022 and I never fixed them. Everything I updated is the Lazy Blocks plugin. Every time Gutenberg changes something, I just need to update a single plugin instead of 20+ plugins. As a lazy person, I feel great when I realize this :)

To this day, I sometimes feel too lazy to construct some blocks, and Lazy Blocks help me out, when I need to ship a site fast. So, the name of the plugin reflects my state of mind as a developer when I need to use it. I'm the type of person who wants to optimize and simplify everything today so I don't have to work harder tomorrow (it doesn't always work out, actually). I like to work, but I like to simplify my life much more, so I consider myself lazy :)

Soon we want to release the paid version of this plugin, and not only me, but also my team work on it. And if this plugin will have commercial success, we will consider renaming the plugin. Therefore, I would like to see the wishes and suggestions here in this GitHub issue.
