### ISSUE TITLE
Release date for update/pro version?

### ISSUE THREAD

**Issue by hj-collab** [nk-crew/lazy-blocks#257]
When can we expect an update or the release of the pro version? Is there any beta available? Thanks

**Comment by hodessy** [comment]
@nk-o Any update at all?

**Comment by jordymeow** [comment]
Really hope it will happen; this plugin needs a Pro version, so that we can help the developer maintaining it. It's so much better than what ACF did with its blocks support.

**Comment by davidwebca** [comment]
Sorry for the notification, but I agree. I'll gladly pay a very large sum of money to have this integrated in my workflow 🔥

**Comment by nk-o** [comment]
Hey guys.

Thank you for your support. The initial version of the Pro plugin is almost ready, we have to finish the site and documentation. So far, it is not possible to devote enough time to this plugin, because we are busy with other premium products. I hope we will release it in 2 weeks.

p.s. please, don't expect anything supernatural from the plugin in the first version, there will be just some of the most requested features.

Regards, nK.

**Comment by CullenJWebb** [comment]
Will we be able to include the pro version inside a custom plugin / theme like we currently can with the repository?

I'm just getting started with LZB and that's my only deal breaker for a pro version 🙂

**Comment by nk-o** [comment]
> Will we be able to include the pro version inside a custom plugin / theme like we currently can with the repository?

Yes, you will be able to include it the same way as the Free plugin 😊

**Comment by nk-o** [comment]
At the moment, my whole family is hospitalized, the children are sick, so the plugin release is delayed for some time

**Comment by nk-o** [comment]
Lazy Block Pro is finally shipped! 🔥 Along with the brand new site https://www.lazyblocks.com

**Comment by davidwebca** [comment]
Nice! 🔥 I'm buying it right away!
