### ISSUE TITLE
Removing a block containing a "save in Meta" field does not clear the post meta field in DB

### ISSUE THREAD

**Issue by janwidmer** [nk-crew/lazy-blocks#294]
### Issue description:
I am using some blocks with fields with the "Save in Meta" Options. Those are mostly Stage components being used at the top of the page to display an large image. The image field uses the option "Save in meta" so that I can also use this image to display teasers to sucht pages.

This works so far. The problem is, that the entry in the post_meta database table is not getting removed properly, when the block is being removed from the page.

Steps to reproduce:
1. Import this block [lzb-export-blocks-2023-08-06.json.zip](https://github.com/nk-crew/lazy-blocks/files/12269894/lzb-export-blocks-2023-08-06.json.zip)
2. Place it on a page and fill out the fields, the field "Bühne Bild" Contains the stage image
3. When saving the page, a db entry to the post_meta table get's made containing the image information
4. When removing this block from the page again, the entry in the post_meta table remains
5. This is a problem, since my `index.php` page checks for the post meta entry to decide if a page title block should be displaye as fallback or not (because the stage block is there) 

### Lazy Blocks Version:
3.4.4

### WordPress Version:
6.2.2

### Any helpful information to reproduce the issue (screenshots, code parts)
A potentiall workaround would be to use the post save filter and somehow figure out if a stage block is in the content and if not, remove the entry in the post_meta table. Another potential workaround could be to use the js actions / filters..

**Comment by nk-o** [comment]
It is a good suggestion, but we should make it better.

I don't think we should remove silently the post meta, because it can be used by 3rd-parties.
Even if the user decides not to use Lazy Blocks anymore, their posts and post templates may still use meta fields.

Also, blocks may be removed by accident and meta will be removed.

We can try to prevent removing such blocks and ask the user in a simple popup first. 
For example:

<img width="1231" alt="Shot 2023-08-16 at 08 58 46" src="https://github.com/nk-crew/lazy-blocks/assets/14810891/f032e4d3-6457-4276-baec-2bf4ac37aa9a">


To make it possible, we should check these things:
- Ensure that we can prevent block removal action using Gutenberg API
- In case the user removes a bunch of blocks, we should parse all selected and inner blocks

**Comment by janwidmer** [comment]
Sounds like a good solution
