### ISSUE TITLE
Function `_load_textdomain_just_in_time` called incorrectly

### ISSUE THREAD

**Issue by misaki-web** [nk-crew/lazy-blocks#325]
Using Lazy Blocks 3.7.0, I've started getting the following error in the file `debug.log` after updating WordPress to version 6.7:

> PHP User Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>lazy-blocks</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php (6114)

**Comment by Amenel** [comment]
This error is unfortunately a real showstopper as it makes access to the admin page on my dev workstation impossible as the login page cannot be displayed. I'm using PHP 8.3.14 and WordPress 6.7.0.

For now, I work around it by setting `WP_DEBUG` to `false`, so that I can log in and work on the website.

**Comment by Amenel** [comment]
I can confirm that the issue is fixed. Many, many thanks to @Fellan-91 and the team!
