### ISSUE TITLE
Yoast not able to read content

### ISSUE THREAD

**Issue by dcp3450** [nk-crew/lazy-blocks#95]
Before using Lazy Blocks in a non-Gutenburg setting, Yoast worked fine and displayed word count and other metrics correctly. It appears Yoast can't see the content generated by Lazy Blocks. Is there a workaround and/or solution to resolve this?

**Comment by nk-o** [comment]
I think Yoast can't work with dynamic Gutenberg blocks https://github.com/Yoast/wordpress-seo/issues/13235

**Comment by nk-o** [comment]
Looks like the RankMath SEO plugin has developer hooks for developers, which may help with dynamic blocks.

We will need to check this https://rankmath.com/kb/content-analysis-api/

Thanks for mentioning in https://wordpress.org/support/topic/rankmath-content-analysis/

p.s. actually, we are not interested in Yoast, since we are using RankMath everywhere :) And this situation just tells us why we should keep using RankMath and why Yoast should die.

**Comment by biabel** [comment]
@nk-o 
Hello Lazyblocks Team,
I need some quick help in customizing Rank Math Pro to use lazyblocks.

How can I customize Rank Math Pro so that it can read and analyze the content from my lazyblocks?

I have read the link from Rank Math itself, unfortunately I don't understand their procedure and can't understand where I have to place and load which script to make the analysis work....

Please for quick help :(

**Comment by GoddamnNoise** [comment]
Hi,

I'm facing the same problem with Lazyblocks and Yoast SEO and I'm not sure if Yoast has all the guilt here or if there is some other problem.

I have Yoast SEO configured to show the excerpt of the post as the meta description but looking at the code there is no meta description at all in those posts which content is generated from Lazyblocks.

While researching this problem I've noticed that if I've a post where the content is generated from Lazyblocks, the function get_the_excerpt() returns an empty string. So, there could be some other problem with the Lazyblock content and this could be stopping Yoast to get the content in some cases.

**Comment by nk-o** [comment]
Good news. In the next Pro plugin update, the "content analysis" feature of Rank Math and Yoast will work with blocks created in Lazy Blocks!

So I will close this issue, the new plugin update will be available the next week.

@GoddamnNoise your issue is different. Gutenberg itself ignores the dynamic blocks when generating excerpts, and as I understand, there is no good solution for now to prevent this behavior.
